### ISSUE TITLE
Рентабельность наличия Тэгов

### ISSUE THREAD

**Issue by ThaHatty-KonstantinErmolaev** [FroggersProgramming/EMPTYprojectAPI#1]
Нужна ли в проекте сущность Tag?

Модель:
https://github.com/FroggersProgramming/EMPTYprojectAPI/blob/df2dbd4a597274d27ac5fb9b5a2c8592b55e3945/app/Models/Tag.php#L1C1-L11C2

Миграция:
https://github.com/FroggersProgramming/EMPTYprojectAPI/blob/df2dbd4a597274d27ac5fb9b5a2c8592b55e3945/database/migrations/2023_10_16_115528_create_tags_table.php#L1C1-L27C3

**Comment by KACHEGAR** [comment]
Нет, не нужны
